from ...core.entities.showtime_seat import ShowtimeSeatBase, BaseModel
from pydantic import Field
from datetime import datetime
from typing import Optional

class ShowtimeSeatCreate(ShowtimeSeatBase):
    """
    Schema for creating a new ShowtimeSeat.
    'id' and timestamps are not included as they are typically generated by the database.
    """
    pass

class ShowtimeSeatUpdate(BaseModel):
    """
    Schema for updating an existing ShowtimeSeat.
    All fields are optional for partial updates.
    """
    id: int = Field(..., description="The unique identifier of the showtime seat to update.")
    showtime_id: Optional[int] = Field(None, description="The ID of the showtime this seat belongs to.")
    theater_seat_id: Optional[int] = Field(None, description="The ID of the specific theater seat.")
    taken_at: Optional[datetime] = Field(None, description="Timestamp when the seat was taken/booked.")
    transaction_id: Optional[int] = Field(None, description="The ID of the transaction associated with this booking.")
    user_id: Optional[int] = Field(None, description="The ID of the user who took this seat.")
1