version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billboard
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"

volumes:
  postgres_data: